development:
  adapter: postgresql
  encoding: unicode
  database: ratingswebsite_development
  pool: 5
  username: ratingswebsite
  password: pass

test:
  adapter: postgresql
  encoding: unicode
  database: ratingswebsite_test
  pool: 5
  username: ratingswebsite
  password: pass
